// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gezhdauazitnymbtmlat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlemhkYXVheml0bnltYnRtbGF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NTYwODIsImV4cCI6MjA1OTUzMjA4Mn0.jdWIaTOVKL30ETu-T23s75APHR3iKKJa7pftyPKVOl8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});